# Generated by Django 5.2 on 2025-05-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skin',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
