# Generated by Django 5.2 on 2025-05-11 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_skin_image_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
