# Generated by Django 5.2 on 2025-05-11 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_usercharater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercharater',
            name='engry',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
