# Generated by Django 5.2 on 2025-05-11 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_usercharater_engry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercharater',
            name='user',
        ),
    ]
