# Generated by Django 5.2 on 2025-05-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_usercharater_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skin',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
