# Generated by Django 5.2 on 2025-05-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_skin_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image_character',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
