# Generated by Django 5.2 on 2025-05-14 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_usercharater_coins_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercharater',
            name='engry',
            field=models.IntegerField(default=1000, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
