# Generated by Django 5.2 on 2025-05-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_usercharater_engry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='user',
        ),
        migrations.AlterField(
            model_name='usercharater',
            name='coins',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
