# Generated by Django 5.2 on 2025-05-15 06:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_userearnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercharater',
            name='last_energy_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
