# Generated by Django 5.2 on 2025-05-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_dailycipher_usercharater_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercharater',
            name='last_mining_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
