# Generated by Django 5.2 on 2025-06-08 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_usercharater_last_mining_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='HafizReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('arabic_text', models.TextField()),
                ('translation', models.TextField(blank=True)),
                ('date_to_show', models.DateField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hafizreading'),
        ),
    ]
