# Generated by Django 5.2 on 2025-06-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_hafizreading_task_reading'),
    ]

    operations = [
        migrations.AddField(
            model_name='miningcard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
