# Generated by Django 5.2 on 2025-06-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_miningcard_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='miningcard',
            name='profit_increase',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
