# Generated by Django 5.2 on 2025-06-08 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_miningcard_profit_increase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='miningcard',
            old_name='profit_increase',
            new_name='profit_per',
        ),
    ]
