# Generated by Django 5.2 on 2025-07-04 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_bank_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='comment',
            field=models.CharField(default=1, max_length=4000),
            preserve_default=False,
        ),
    ]
